In [1]:
import pandas as pd
import xlrd
import tensorflow as tf
import sys
import urllib3
import requests
import numpy as np
from pandas import ExcelWriter
from bs4 import BeautifulSoup
from sklearn.model_selection import train_test_split

sys.path.append('C:\python36\Scripts')

//anaconda/lib/python3.5/importlib/_bootstrap.py:222: RuntimeWarning: compiletime version 3.6 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.5
  return f(*args, **kwds)

In [2]:
df_twelvemonth = pd.read_excel(open('project_final_data.xls','rb'))

In [3]:
#Create columns for expected class based on one year price percentage change 
#Note: some rows do not have this field so the class is assigned NA for those rows 
class_list = []
for row in df_twelvemonth.iterrows():
    if type (row[1]['Equity Offering Values - 1 Year Return (%)']) is not str:
        if row[1]['Equity Offering Values - 1 Year Return (%)'] >= 0 :
            class_list.append('increase')
        else:
            class_list.append('decrease')
    else:
        class_list.append('NA')
df_twelvemonth['Class'] = class_list
df_twelvemonth.head()

,All Transactions Announced Date,All Transactions Announced Month,All Transactions Announced Day,All Transactions Announced Year,Target/Issuer,Exchange,Ticker,"Total Transaction Value ($USDmm, Historical rate)","Price Per Share ($USD, Historical rate)",Public Offerings Offer Date,...,"Overallotment Amount ($USDmm, Historical rate)",Equity Offering Values - 1 Day Return (%),Equity Offering Values - 1 Month Return (%),Equity Offering Values - 3 Month Return (%),Equity Offering Values - 1 Year Return (%),Percent of Net Proceeds to Company (%),Percent of Net Proceeds to Shareholders (%),Headquarters - Country [Target/Issuer],Primary Industry [Target/Issuer],Class
0,2017-03-07,3,7,2017,"Warrior Met Coal, Inc. (NYSE:HCC)",NYSE,HCC,316.67,19.00,2017-04-12,...,47.50,-5.26,-8.11,-1.32,23.16,0.0,100.0,United States,Steel,increase
1,2017-03-09,3,9,2017,Tocagen Inc. (NasdaqGS:TOCA),NasdaqGS,TOCA,85.00,10.00,2017-04-12,...,12.75,24.50,58.40,-0.60,9.6,100.0,0.0,United States,Biotechnology,increase
2,2017-03-13,3,13,2017,"Yext, Inc. (NYSE:YEXT)",NYSE,YEXT,115.50,11.00,2017-04-12,...,17.33,21.91,23.91,23.00,14.18,100.0,0.0,United States,Internet Software and Services,increase
3,2017-03-17,3,17,2017,Cadence Bancorporation (NYSE:CADE),NYSE,CADE,150.00,20.00,2017-04-12,...,22.50,7.75,9.25,11.40,38.65,100.0,0.0,United States,Regional Banks,increase
4,2017-03-15,3,15,2017,Netshoes (Cayman) Limited (NYSE:NETS),NYSE,NETS,148.50,18.00,2017-04-11,...,22.28,-10.56,-6.94,9.22,-69.33,100.0,0.0,Brazil,Internet and Direct Marketing Retail,decrease

In [4]:
df_twelvemonth = df_twelvemonth.drop(['Target/Issuer', 'Ticker', 'Public Offerings Offer Date', 'All Transactions Announced Date'], axis=1)
print(len(df_twelvemonth.index))
df_twelvemonth = df_twelvemonth.drop(df_twelvemonth.columns[15], axis=1) # drop column with 1 year returns
df_twelvemonth = df_twelvemonth[df_twelvemonth.Class != "NA"]
df_twelvemonth.to_csv("Project.csv", index=False, header=False)
print(len(df_twelvemonth.index))



train, test = train_test_split(df_twelvemonth, test_size=0.1)
train.to_csv("./data/ipo_data.csv", index=False, header=False)
test.to_csv("./data/ipo_test.csv", index=False, header=False)

dfList = df_twelvemonth['Exchange'].tolist()
print (len(set(dfList)))
dfList = df_twelvemonth['Headquarters - Country [Target/Issuer]'].tolist()
print (len(set(dfList)))
dfList = df_twelvemonth['Primary Industry [Target/Issuer]'].tolist()
print (len(set(dfList)))

4624
4173
27
46
147